include:
  - board: eyelash_nano
    shield: offsetkey_peripheral_left
    artifact-name: offsetkey_peripheral_left
  - board: eyelash_nano
    shield: offsetkey_peripheral_right
    artifact-name: offsetkey_peripheral_right
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
  - board: eyelash_nano
    shield: settings_reset
    artifact-name: settings_reset
