include:
  - board: eyelash_nano
    shield: offsetkey_left 
  - board: eyelash_nano
    shield: offsetkey_right 
    cmake-args: -DDTS_EXTRA_CPPFLAGS=-DMOUSE_PS2_ALT_PINS
  - board: eyelash_nano
    shield: settings_reset
