CONFIG_INPUT=y
CONFIG_ZMK_EXT_POWER=y

CONFIG_PMW3610=y
CONFIG_PMW3610_SWAP_XY=y
CONFIG_PMW3610_INVERT_X=y
CONFIG_PMW3610_INVERT_Y=n
CONFIG_PMW3610_REPORT_INTERVAL_MIN=12
CONFIG_PMW3610_INIT_POWER_UP_EXTRA_DELAY_MS=200

# === Studio (Central only) ===
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_BLE_MANAGEMENT=y
CONFIG_ZMK_BLE_MANAGEMENT_STUDIO_RPC=y

# === Runtime Input Processor (Central only) ===
CONFIG_ZMK_RUNTIME_INPUT_PROCESSOR=y
CONFIG_ZMK_RUNTIME_INPUT_PROCESSOR_STUDIO_RPC=y

# === Settings RPC (Central only) ===
CONFIG_ZMK_SETTINGS_RPC=y
CONFIG_ZMK_SETTINGS_RPC_STUDIO=y

# === Runtime Sensor Rotate (Encoder, Central only) ===
CONFIG_ZMK_RUNTIME_SENSOR_ROTATE=y
CONFIG_ZMK_RUNTIME_SENSOR_ROTATE_STUDIO_RPC=y

# === Settings (Central only) ===
CONFIG_SETTINGS=y

# === Battery (Central only) ===
CONFIG_ZMK_BATTERY_HISTORY=n
CONFIG_ZMK_BATTERY_HISTORY_STUDIO_RPC=n

# === Split (Central only) ===
CONFIG_ZMK_SPLIT_RELAY_EVENT=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_SPLIT_RUN_STACK_SIZE=1024
CONFIG_ZMK_SETTINGS_SAVE_DEBOUNCE=10000
